# **Step 1: Getting Datasets**

# **Step 1.1: Getting file from Kaggle(1st Source of Dataset)**

In [1]:
import pandas as pd
import time

# Before running this code download the kaggle dataset available on below link to your local machine 
# link to dataser: https://www.kaggle.com/datasets/mexwell/ucs-satellite-database?select=satellites.csv


# CSV file normally contains ',' as separator but this file contains';' as column separator so below code is done accordingly
df_satellites = pd.read_csv("satellites.csv", sep=";", engine="python")
df_satellites.head()

,"Name of Satellite, Alternate Names",Current Official Name of Satellite,Country/Org of UN Registry,Country of Operator/Owner,Operator/Owner,Users,Purpose,Detailed Purpose,Class of Orbit,Type of Orbit,...,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67
0,1HOPSAT-TD (1st-generation High Optical Perfor...,1HOPSAT-TD,NR,USA,Hera Systems,Commercial,Earth Observation,Infrared Imaging,LEO,Non-Polar Inclined,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AAC AIS-Sat1 (Kelpie 1),AAC AIS-Sat1 (Kelpie 1),United Kingdom,United Kingdom,AAC Clyde Space,Commercial,Earth Observation,Automatic Identification System (AIS),LEO,Sun-Synchronous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aalto-1,Aalto-1,Finland,Finland,Aalto University,Civil,Technology Development,NaN,LEO,Sun-Synchronous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AAt-4,AAt-4,Denmark,Denmark,University of Aalborg,Civil,Earth Observation,Automatic Identification System (AIS),LEO,Sun-Synchronous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"ABS-2 (Koreasat-8, ST-3)",ABS-2,NR,Multinational,Asia Broadcast Satellite Ltd.,Commercial,Communications,NaN,GEO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# **Step 1.2: Getting file from Celestrak API (2nd Source of Dataset)**

In [2]:
import requests

url = "https://celestrak.org/NORAD/elements/gp.php?GROUP=starlink&FORMAT=json"

headers = {
    "User-Agent": "my-satellite-script/1.0 (contact: supriyagosavi14@gmail.com)",
    "Accept": "application/json"
}

response = requests.get(url, headers=headers)

print(response.status_code)
print(response.text[:200])  # inspect response safely before .json()

data = response.json()

200
[{"OBJECT_NAME":"STARLINK-1008","OBJECT_ID":"2019-074B","EPOCH":"2026-04-14T01:10:17.964192","MEAN_MOTION":15.34731974,"ECCENTRICITY":0.0003397,"INCLINATION":53.1548,"RA_OF_ASC_NODE":13.8699,"ARG_OF_P

In [3]:

df_live = pd.DataFrame(data)
df_live.shape
df_live.head()

,OBJECT_NAME,OBJECT_ID,EPOCH,MEAN_MOTION,ECCENTRICITY,INCLINATION,RA_OF_ASC_NODE,ARG_OF_PERICENTER,MEAN_ANOMALY,EPHEMERIS_TYPE,CLASSIFICATION_TYPE,NORAD_CAT_ID,ELEMENT_SET_NO,REV_AT_EPOCH,BSTAR,MEAN_MOTION_DOT,MEAN_MOTION_DDOT
0,STARLINK-1008,2019-074B,2026-04-14T01:10:17.964192,15.347320,0.000340,53.1548,13.8699,150.0326,210.0871,0,U,44714,999,35429,0.000953,0.000323,0.000000
1,STARLINK-1012,2019-074F,2026-04-14T04:15:49.829184,15.340619,0.000381,53.1593,13.5345,136.1320,223.9986,0,U,44718,999,35430,0.000685,0.000226,0.000000
2,STARLINK-1017,2019-074L,2026-04-13T17:15:07.610112,15.274593,0.000346,53.0529,9.4415,144.9682,215.1543,0,U,44723,999,35431,0.000821,0.000221,0.000000
3,STARLINK-1019,2019-074M,2026-04-14T04:00:01.998720,15.950034,0.000449,53.0364,316.6929,270.0053,346.9528,0,U,44724,999,608,0.000467,0.001828,0.000024
4,STARLINK-1020,2019-074N,2026-04-14T02:38:03.009120,15.331425,0.000305,53.1596,39.0584,138.7127,221.4106,0,U,44725,999,35392,0.001154,0.000373,0.000000

# **Step 2 : Cleaning Datasets**

# **Step 2.1: Cleaning of Dataset from Kaggle: Satellite.csv**

In [ ]:
df_satellites.head(3)

,"Name of Satellite, Alternate Names",Current Official Name of Satellite,Country/Org of UN Registry,Country of Operator/Owner,Operator/Owner,Users,Purpose,Detailed Purpose,Class of Orbit,Type of Orbit,...,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67
0,1HOPSAT-TD (1st-generation High Optical Perfor...,1HOPSAT-TD,NR,USA,Hera Systems,Commercial,Earth Observation,Infrared Imaging,LEO,Non-Polar Inclined,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AAC AIS-Sat1 (Kelpie 1),AAC AIS-Sat1 (Kelpie 1),United Kingdom,United Kingdom,AAC Clyde Space,Commercial,Earth Observation,Automatic Identification System (AIS),LEO,Sun-Synchronous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aalto-1,Aalto-1,Finland,Finland,Aalto University,Civil,Technology Development,NaN,LEO,Sun-Synchronous,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_satellites.columns

Index(['Name of Satellite, Alternate Names',
       'Current Official Name of Satellite', 'Country/Org of UN Registry',
       'Country of Operator/Owner', 'Operator/Owner', 'Users', 'Purpose',
       'Detailed Purpose', 'Class of Orbit', 'Type of Orbit',
       'Longitude of GEO (degrees)', 'Perigee (km)', 'Apogee (km)',
       'Eccentricity', 'Inclination (degrees)', 'Period (minutes)',
       'Launch Mass (kg.)', 'Dry Mass (kg.)', 'Power (watts)',
       'Date of Launch', 'Expected Lifetime (yrs.)', 'Contractor',
       'Country of Contractor', 'Launch Site', 'Launch Vehicle',
       'COSPAR Number', 'NORAD Number', 'Comments', 'Unnamed: 28',
       'Source Used for Orbital Data', 'Source', 'Source.1', 'Source.2',
       'Source.3', 'Source.4', 'Source.5', 'Source.6', 'Unnamed: 37',
       'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41',
       'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45',
       'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49',
       'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53',
       'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57',
       'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61',
       'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65',
       'Unnamed: 66', 'Unnamed: 67'],
      dtype='object')

Removing unnecessary added columns

In [ ]:
df_satellites = df_satellites.loc[:, ~df_satellites.columns.str.contains('^Unnamed')]
df_satellites.columns

Index(['Name of Satellite, Alternate Names',
       'Current Official Name of Satellite', 'Country/Org of UN Registry',
       'Country of Operator/Owner', 'Operator/Owner', 'Users', 'Purpose',
       'Detailed Purpose', 'Class of Orbit', 'Type of Orbit',
       'Longitude of GEO (degrees)', 'Perigee (km)', 'Apogee (km)',
       'Eccentricity', 'Inclination (degrees)', 'Period (minutes)',
       'Launch Mass (kg.)', 'Dry Mass (kg.)', 'Power (watts)',
       'Date of Launch', 'Expected Lifetime (yrs.)', 'Contractor',
       'Country of Contractor', 'Launch Site', 'Launch Vehicle',
       'COSPAR Number', 'NORAD Number', 'Comments',
       'Source Used for Orbital Data', 'Source', 'Source.1', 'Source.2',
       'Source.3', 'Source.4', 'Source.5', 'Source.6'],
      dtype='object')

In [ ]:
df_satellites.head()

,"Name of Satellite, Alternate Names",Current Official Name of Satellite,Country/Org of UN Registry,Country of Operator/Owner,Operator/Owner,Users,Purpose,Detailed Purpose,Class of Orbit,Type of Orbit,...,NORAD Number,Comments,Source Used for Orbital Data,Source,Source.1,Source.2,Source.3,Source.4,Source.5,Source.6
0,1HOPSAT-TD (1st-generation High Optical Perfor...,1HOPSAT-TD,NR,USA,Hera Systems,Commercial,Earth Observation,Infrared Imaging,LEO,Non-Polar Inclined,...,44859,Pathfinder for planned earth observation const...,JMSatcat/3_20,https://spaceflightnow.com/2019/12/11/indias-5...,https://www.herasys.com/,NaN,NaN,NaN,NaN,NaN
1,AAC AIS-Sat1 (Kelpie 1),AAC AIS-Sat1 (Kelpie 1),United Kingdom,United Kingdom,AAC Clyde Space,Commercial,Earth Observation,Automatic Identification System (AIS),LEO,Sun-Synchronous,...,55107,Provide AIS information to Orbcomm.,JMSatcat/9_23,https://www.aac-clyde.space/articles/aac-clyde...,NaN,NaN,NaN,NaN,NaN,NaN
2,Aalto-1,Aalto-1,Finland,Finland,Aalto University,Civil,Technology Development,NaN,LEO,Sun-Synchronous,...,42775,Technology development and education.,JMSatcat/10_17,https://directory.eoportal.org/web/eoportal/sa...,NaN,http://www.planet4589.org/space/log/satcat.txt,NaN,NaN,NaN,NaN
3,AAt-4,AAt-4,Denmark,Denmark,University of Aalborg,Civil,Earth Observation,Automatic Identification System (AIS),LEO,Sun-Synchronous,...,41460,Carries AIS system.,Space50,http://spaceflightnow.com/2016/04/26/soyuz-bla...,NaN,http://space50.org/objekt.php?mot=2016-025E&ja...,NaN,NaN,NaN,NaN
4,"ABS-2 (Koreasat-8, ST-3)",ABS-2,NR,Multinational,Asia Broadcast Satellite Ltd.,Commercial,Communications,NaN,GEO,NaN,...,39508,"32 C-band, 51 Ku-band, and 6 Ka-band transpond...",ZARYA,http://www.absatellite.net/satellite-fleet/?sa...,NaN,http://www.zarya.info/Diaries/Launches/Launche...,http://www.absatellite.net/2010/10/13/asia-bro...,http://www.spacenews.com/article/satellite-tel...,NaN,NaN

Keep everything up to and including NORAD Number:

In [ ]:
df_satellites = df_satellites.loc[:, :'NORAD Number']
df_satellites.columns

Index(['Name of Satellite, Alternate Names',
       'Current Official Name of Satellite', 'Country/Org of UN Registry',
       'Country of Operator/Owner', 'Operator/Owner', 'Users', 'Purpose',
       'Detailed Purpose', 'Class of Orbit', 'Type of Orbit',
       'Longitude of GEO (degrees)', 'Perigee (km)', 'Apogee (km)',
       'Eccentricity', 'Inclination (degrees)', 'Period (minutes)',
       'Launch Mass (kg.)', 'Dry Mass (kg.)', 'Power (watts)',
       'Date of Launch', 'Expected Lifetime (yrs.)', 'Contractor',
       'Country of Contractor', 'Launch Site', 'Launch Vehicle',
       'COSPAR Number', 'NORAD Number'],
      dtype='object')

Standardise the Column names: All in lower case and without spaces

In [ ]:
df_satellites.columns = df_satellites.columns.str.lower().str.replace(' ', '_')
df_satellites.columns

Index(['name_of_satellite,_alternate_names',
       'current_official_name_of_satellite', 'country/org_of_un_registry',
       'country_of_operator/owner', 'operator/owner', 'users', 'purpose',
       'detailed_purpose', 'class_of_orbit', 'type_of_orbit',
       'longitude_of_geo_(degrees)', 'perigee_(km)', 'apogee_(km)',
       'eccentricity', 'inclination_(degrees)', 'period_(minutes)',
       'launch_mass_(kg.)', 'dry_mass_(kg.)', 'power_(watts)',
       'date_of_launch', 'expected_lifetime_(yrs.)', 'contractor',
       'country_of_contractor', 'launch_site', 'launch_vehicle',
       'cospar_number', 'norad_number'],
      dtype='object')

In [ ]:
df_satellites.columns = (
    df_satellites.columns
    .str.lower()
    .str.replace('(', '_', regex=False)   # replace ( with _
    .str.replace('/', '_', regex=False)   # replace ( with _
    .str.replace(')', '', regex=False)    # remove )
    .str.replace(r'[^\w\s]', '', regex=True)  # remove other special chars
    .str.replace(' ', '_')                # spaces → underscore
    .str.replace('__', '_')
)
df_satellites.columns

Index(['name_of_satellite_alternate_names',
       'current_official_name_of_satellite', 'country_org_of_un_registry',
       'country_of_operator_owner', 'operator_owner', 'users', 'purpose',
       'detailed_purpose', 'class_of_orbit', 'type_of_orbit',
       'longitude_of_geo_degrees', 'perigee_km', 'apogee_km', 'eccentricity',
       'inclination_degrees', 'period_minutes', 'launch_mass_kg',
       'dry_mass_kg', 'power_watts', 'date_of_launch', 'expected_lifetime_yrs',
       'contractor', 'country_of_contractor', 'launch_site', 'launch_vehicle',
       'cospar_number', 'norad_number'],
      dtype='object')

Decide Columns to keep for analysis

In [ ]:
cols_to_keep = [
    'current_official_name_of_satellite',
    'country_of_operator_owner',
    'operator_owner',
    'users',
    'purpose',
    'class_of_orbit',
    'type_of_orbit',
    'perigee_km',
    'apogee_km',
    'inclination_degrees',
    'period_minutes',
    'launch_mass_kg',
    'date_of_launch',
    'expected_lifetime_yrs',
    'launch_site',
    'launch_vehicle',
    'norad_number'
]

new_satellite_data = df_satellites[cols_to_keep]
new_satellite_data.head(3)

,current_official_name_of_satellite,country_of_operator_owner,operator_owner,users,purpose,class_of_orbit,type_of_orbit,perigee_km,apogee_km,inclination_degrees,period_minutes,launch_mass_kg,date_of_launch,expected_lifetime_yrs,launch_site,launch_vehicle,norad_number
0,1HOPSAT-TD,USA,Hera Systems,Commercial,Earth Observation,LEO,Non-Polar Inclined,566.0,576.0,"36,9","96,08",22.0,12/11/19,"0,5",Satish Dhawan Space Centre,PSLV,44859
1,AAC AIS-Sat1 (Kelpie 1),United Kingdom,AAC Clyde Space,Commercial,Earth Observation,LEO,Sun-Synchronous,637.0,654.0,98,95,4.0,1/3/23,NaN,Cape Canaveral,Falcon 9,55107
2,Aalto-1,Finland,Aalto University,Civil,Technology Development,LEO,Sun-Synchronous,497.0,517.0,"97,45","94,7",5.0,6/23/17,2,Satish Dhawan Space Centre,PSLV,42775

Check for Duplicates

In [ ]:
new_satellite_data.duplicated().sum()

np.int64(7)

Dropping Duplicates

In [ ]:
new_satellite_data=new_satellite_data.drop_duplicates()
new_satellite_data.duplicated().sum()

np.int64(0)

Checking for Null values

In [ ]:
round((new_satellite_data.isna().sum() / len(new_satellite_data)) * 100)

current_official_name_of_satellite     0.0
country_of_operator_owner              0.0
operator_owner                         0.0
users                                  0.0
purpose                                0.0
class_of_orbit                         0.0
type_of_orbit                          9.0
perigee_km                             0.0
apogee_km                              0.0
inclination_degrees                    0.0
period_minutes                         1.0
launch_mass_kg                         3.0
date_of_launch                         0.0
expected_lifetime_yrs                 28.0
launch_site                            0.0
launch_vehicle                         0.0
norad_number                           0.0
dtype: float64

Drop rows where period_minutes is missing

In [ ]:
new_satellite_data = new_satellite_data.dropna(subset=['period_minutes'])

In [ ]:
round((new_satellite_data.isna().sum() / len(new_satellite_data)) * 100)

current_official_name_of_satellite     0.0
country_of_operator_owner              0.0
operator_owner                         0.0
users                                  0.0
purpose                                0.0
class_of_orbit                         0.0
type_of_orbit                          9.0
perigee_km                             0.0
apogee_km                              0.0
inclination_degrees                    0.0
period_minutes                         0.0
launch_mass_kg                         3.0
date_of_launch                         0.0
expected_lifetime_yrs                 27.0
launch_site                            0.0
launch_vehicle                         0.0
norad_number                           0.0
dtype: float64

Fill missing values in type_of_orbit launch_mass_kg and expected_lifetime_yrs with "unknown"

In [ ]:
new_satellite_data['type_of_orbit'] = new_satellite_data['type_of_orbit'].fillna('unknown')
new_satellite_data['launch_mass_kg'] = new_satellite_data['launch_mass_kg'].fillna('unknown')
new_satellite_data['expected_lifetime_yrs'] = new_satellite_data['expected_lifetime_yrs'].fillna('unknown')

In [ ]:
round((new_satellite_data.isna().sum() / len(new_satellite_data)) * 100)

current_official_name_of_satellite    0.0
country_of_operator_owner             0.0
operator_owner                        0.0
users                                 0.0
purpose                               0.0
class_of_orbit                        0.0
type_of_orbit                         0.0
perigee_km                            0.0
apogee_km                             0.0
inclination_degrees                   0.0
period_minutes                        0.0
launch_mass_kg                        0.0
date_of_launch                        0.0
expected_lifetime_yrs                 0.0
launch_site                           0.0
launch_vehicle                        0.0
norad_number                          0.0
dtype: float64

In [ ]:
new_satellite_data.describe()

        perigee_km    apogee_km  norad_number
count  7493.000000  7493.000000   7497.000000
mean    432.585780   441.737848  47867.455916
std     214.864258   220.348926   6565.140133
min       1.000000     1.000000   7530.000000
25%     348.000000   351.000000  44860.000000
50%     538.000000   541.000000  48406.000000
75%     549.000000   561.000000  53070.000000
max     989.000000   997.000000  62684.000000

The min value in perigee and Apogee looks suspicious, need to look into those rows

In [ ]:
suspicious_data = new_satellite_data[
    (new_satellite_data['perigee_km'] < 30) &
    (new_satellite_data['apogee_km'] < 30)
]

suspicious_data.shape

(720, 17)

In [ ]:
suspicious_data.head(10)

,current_official_name_of_satellite,country_of_operator_owner,operator_owner,users,purpose,class_of_orbit,type_of_orbit,perigee_km,apogee_km,inclination_degrees,period_minutes,launch_mass_kg,date_of_launch,expected_lifetime_yrs,launch_site,launch_vehicle,norad_number
73,Amsat-Oscar 7,USA,AMSAT-NA,Civil,Communications,LEO,Polar,1.440,1.459,"101,4","114,9",29.0,11/15/74,unknown,Vandenberg AFB,Delta 2310,7530
171,Beidou 2-12,China,Chinese Ministry of National Defense,Military/Government,Navigation/Global Positioning,MEO,Non-Polar Inclined,21.460,21.595,"55,16","773,19",2.2,4/28/12,8,Xichang Satellite Launch Center,Long March 3B,38250
172,Beidou 2-13,China,Chinese Ministry of National Defense,Military/Government,Navigation/Global Positioning,MEO,Non-Polar Inclined,21.452,21.603,"55,1","773,21",2.2,4/28/12,8,Xichang Satellite Launch Center,Long March 3B,38251
173,Beidou 2-15,China,Chinese Ministry of National Defense,Military/Government,Navigation/Global Positioning,MEO,Non-Polar Inclined,21.477,21.574,55,"773,1",3.8,9/18/12,8,Xichang Satellite Launch Center,Long March 3B,38775
179,Beidou 3M-1S,China,Chinese Ministry of National Defense,Military/Government,Navigation/Global Positioning,MEO,Non-Polar Inclined,21.520,21.549,55,"773,2",800.0,7/25/15,8,Xichang Satellite Launch Center,Long March 3B,40748
180,Beidou 3M-2S,China,Chinese Ministry of National Defense,Military/Government,Navigation/Global Positioning,MEO,Non-Polar Inclined,21.521,21.550,55,"773,3",800.0,7/25/15,8,Xichang Satellite Launch Center,Long March 3B,40749
181,Beidou 3-M1,China,Chinese Ministry of National Defense,Military/Government,Navigation/Global Positioning,MEO,unknown,21.506,21.549,55,"773,2",800.0,11/5/17,8,Xichang Satellite Launch Center,Long March 3B,43001
182,Beidou 3-23,China,Chinese Ministry of National Defense,Military/Government,Navigation/Global Positioning,MEO,unknown,21.509,21.561,55,"773,2",800.0,9/22/19,8,Xichang Satellite Launch Center,Long March 3B,44542
183,Beidou 3-24,China,Chinese Ministry of National Defense,Military/Government,Navigation/Global Positioning,MEO,unknown,21.515,21.554,55,"773,2",800.0,9/22/19,8,Xichang Satellite Launch Center,Long March 3B,44543
184,Beidou 3-25,China,Chinese Ministry of National Defense,Military/Government,Navigation/Global Positioning,MEO,unknown,21.541,22.549,55,"773,2",800.0,11/5/17,8,Xichang Satellite Launch Center,Long March 3B,43002

In [ ]:
suspicious_data['users'].value_counts()

users
Commercial             526
Military                86
Military/Commercial     65
Military/Government     29
Government              11
Civil                    2
Military                 1
Name: count, dtype: int64

In [84]:
df_live.columns

Index(['OBJECT_NAME', 'OBJECT_ID', 'EPOCH', 'MEAN_MOTION', 'ECCENTRICITY',
       'INCLINATION', 'RA_OF_ASC_NODE', 'ARG_OF_PERICENTER', 'MEAN_ANOMALY',
       'EPHEMERIS_TYPE', 'CLASSIFICATION_TYPE', 'NORAD_CAT_ID',
       'ELEMENT_SET_NO', 'REV_AT_EPOCH', 'BSTAR', 'MEAN_MOTION_DOT',
       'MEAN_MOTION_DDOT'],
      dtype='object')

In [90]:
df_live.head()

,OBJECT_NAME,OBJECT_ID,EPOCH,MEAN_MOTION,ECCENTRICITY,INCLINATION,RA_OF_ASC_NODE,ARG_OF_PERICENTER,MEAN_ANOMALY,EPHEMERIS_TYPE,CLASSIFICATION_TYPE,NORAD_CAT_ID,ELEMENT_SET_NO,REV_AT_EPOCH,BSTAR,MEAN_MOTION_DOT,MEAN_MOTION_DDOT
0,STARLINK-1008,2019-074B,2026-04-13T17:21:25.404480,15.347026,0.000343,53.1550,15.3917,147.8573,212.2639,0,U,44714,999,35424,0.000682,0.000229,0.000000
1,STARLINK-1012,2019-074F,2026-04-13T17:19:06.904416,15.340395,0.000382,53.1591,15.6661,138.6970,221.4322,0,U,44718,999,35423,0.000685,0.000226,0.000000
2,STARLINK-1017,2019-074L,2026-04-13T17:15:07.610976,15.274593,0.000346,53.0529,9.4415,144.9683,215.1544,0,U,44723,999,35431,0.000821,0.000221,0.000000
3,STARLINK-1019,2019-074M,2026-04-14T00:00:02.000160,15.949033,0.000440,53.0370,317.5488,269.3623,110.0597,0,U,44724,999,605,0.000618,0.002416,0.000034
4,STARLINK-1020,2019-074N,2026-04-13T20:22:33.564576,15.331217,0.000308,53.1595,40.2748,138.4597,221.6639,0,U,44725,999,35388,0.001064,0.000343,0.000000